openapi: 3.2.0
info:
  title: RDM Indicator Classification API
  description: Reference Data Manager API
  termsOfService: None
  contact:
    name: UNICEF
    url: https://data.unicef.org/
    email: data@unicef.org
  version: v2.0
servers:
- url: https://rdmapi.unicef.org
tags:
- name: IndicatorClassification
paths:
  /api/IndicatorClassifications:
    get:
      tags:
      - IndicatorClassification
      summary: Get the list of all indicator classifications
      operationId: IndicatorClassification_GetClassifications
      responses:
        '200':
          description: The list of all indicator classifications. For example, "Is SDG Indicator", "Is SOWC", "Is Emergency indicator", etc.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndicatorClassificationItem'
components:
  schemas:
    IndicatorClassificationItem:
      type: object
      required:
      - iclassId
      properties:
        iclassId:
          type: integer
          format: int32
        name:
          type: string
        editedBy:
          type: string
        editedDate:
          type: string
        type:
          type: string
        value:
          type: string
        code:
          type: string
x-generator: NSwag v14.0.2.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
