swagger: '2.0'
info:
  title: GeoSight Basemap Custodian API
  version: v1.0.0
host: geosight.unicef.org
basePath: /api/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
security:
- ApiKey Auth: []
tags:
- name: Custodian
paths:
  /api/custodians:
    get:
      tags:
      - Custodian
      summary: Get the list of all indicator/region series custodians
      operationId: Custodian_GetCustodians
      produces:
      - application/json
      responses:
        '200':
          x-nullable: false
          description: The list of all indicator/region series custodians
          schema:
            type: array
            items:
              $ref: '#/definitions/CustodianItem'
definitions:
  CustodianItem:
    type: object
    required:
    - id
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      editedBy:
        type: string
      editedDate:
        type: string
      code:
        type: string
securityDefinitions:
  ApiKey Auth:
    type: apiKey
    in: header
    name: Authorization
